db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/food_delivery_db?useSSL=true&sslMode=VERIFY_IDENTITY&characterEncoding=UTF-8&serverTimezone=UTC
db.username=4GZ4scbbci9yLyb.root
db.password=ETp7DO4YQ1QUHbng